# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Todo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Todo
  pod 'SnapKit'
  pod 'Then'
  pod 'Moya'
  pod 'HandyJSON', '~> 4.1.1'
  pod 'Kingfisher'
  pod 'EmptyDataSet-Swift'
  target 'TodoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
